--- #YAML:1.0
name:         AI-NaiveBayes1
version:      2.011
version_from: NaiveBayes1.pm
author:
  - Vlado Keselj https://web.cs.dal.ca/~vlado
licence: perl
installdirs:  site
requires:
    YAML:                          0.0
distribution_type: module
